### ISSUE TITLE
Research mobile wallet usage

### ISSUE THREAD

**Issue by chriseth** [ethereum/ethendance#6]
Research how mobile wallets are used, whether the QR codes are standardized, how new users can pay for the gas as easy as possible.

**Comment by chfast** [comment]
# Test contract address

0xa74476443119A942dE498590Fe1f2454d7D4aC0d (GNT)

https://www.the-qrcode-generator.com/
![image](https://cloud.githubusercontent.com/assets/573380/24051489/7c7cac98-0b32-11e7-8a32-5189e9d833ec.png)

https://etherscan.io/address/0xa74476443119A942dE498590Fe1f2454d7D4aC0d
![image](https://cloud.githubusercontent.com/assets/573380/24051566/bf42907e-0b32-11e7-8d3a-db92984cd886.png)

http://goqr.me
![image](https://cloud.githubusercontent.com/assets/573380/24051606/eb450080-0b32-11e7-8681-939f2bd0d9e9.png)




## LΞTH
https://www.inzhoop.com/

- In beta so probably not available to everyone.

## Jaxx
https://jaxx.io
https://play.google.com/store/apps/details?id=com.kryptokit.jaxx

- All 3 test passed.
- Allows you to add data as a text in advanced options.
